#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/script/prompt
source $DOTFILES_ROOT/script/linkfile

set -e

install_dotfiles () {
  echo
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_dependencies () {
  # If we're on a Mac, let's install and setup homebrew.
  if [ "$(uname -s)" == "Darwin" ]
  then
    echo
    info "installing dependencies"
    if source bin/dot | while read -r data; do "$data"; done
    then
      success "dependencies installed"
      echo
      echo "Now updating dependencies..."
      pip3 install --upgrade setuptools
    else
      fail "error installing dependencies"
    fi
  fi
}

beche_fontSetup () {
  # install Source Code Pro nerd font
  sudo cp $HOME/.dotfiles/fonts/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
  sudo cp $HOME/.dotfiles/fonts/Caskaydia\ Cove\ Nerd\ Font\ Complete.ttf /Library/Fonts
  success "Source Code Pro font and Caskaydia Cove font copied successfully!"
}

install_dotfiles
install_dependencies

beche_fontSetup

success 'Badass macOS terminal installed!'
