#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/script/prompt

set -e

# Run Homebrew through the Brewfile
info "running brew bundle"

brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

success "brew bundle"
